### ISSUE TITLE
Error occurred when executing Zoe-DepthMapPreprocessor

### ISSUE THREAD

**Issue by rovo79** [Fannovel16/comfyui_controlnet_aux#2]
Running this on Mac OS with MPS support in nightly Pytorch.

```
!!! Exception during processing !!!
Traceback (most recent call last):
  File "~/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "~/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "~/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "~/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/zoe.py", line 18, in execute
    return (common_annotator_call(model, image), )
  File "~/ComfyUI/custom_nodes/comfyui_controlnet_aux/utils.py", line 28, in common_annotator_call
    np_result = model(np_image, output_type="numpy", **kwargs)
  File "~/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/zoe/__init__.py", line 56, in __call__
    depth = self.model.infer(image_depth)
  File "~/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/zoe/zoedepth/models/depth_model.py", line 126, in infer
    return self.infer_with_flip_aug(x, pad_input=pad_input, **kwargs)
  File "~/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/zoe/zoedepth/models/depth_model.py", line 110, in infer_with_flip_aug
    out = self._infer_with_pad_aug(x, pad_input=pad_input, **kwargs)
  File "~/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/zoe/zoedepth/models/depth_model.py", line 88, in _infer_with_pad_aug
    out = self._infer(x)
  File "~/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/zoe/zoedepth/models/depth_model.py", line 55, in _infer
    return self(x)['metric_depth']
  File "~/.pyenv/versions/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "~/.pyenv/versions/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "~/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/zoe/zoedepth/models/zoedepth/zoedepth_v1.py", line 144, in forward
    rel_depth, out = self.core(x, denorm=denorm, return_rel_depth=True)
  File "~/.pyenv/versions/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "~/.pyenv/versions/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "~/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/zoe/zoedepth/models/base_models/midas.py", line 263, in forward
    x = self.prep(x)
  File "~/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/zoe/zoedepth/models/base_models/midas.py", line 187, in __call__
    return self.normalization(self.resizer(x))
  File "~/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/zoe/zoedepth/models/base_models/midas.py", line 174, in __call__
    return nn.functional.interpolate(x, (height, width), mode='bilinear', align_corners=True)
  File "~/.pyenv/versions/comfyui/lib/python3.10/site-packages/torch/nn/functional.py", line 3926, in interpolate
    raise TypeError(
TypeError: expected size to be one of int or Tuple[int] or Tuple[int, int] or Tuple[int, int, int], but got size with types [<class 'numpy.int64'>, <class 'numpy.int64'>]
```

I have no idea if this is related but noticed that in:
custom_nodes/comfyui_controlnet_aux/node_wrappers/zoe.py

it can't import
```import controlnet_aux```

More likely I'm thinking this must have something to do with the way torch is casting integers.

**Comment by Fannovel16** [comment]
I just tested on ComfyUI_windows_portable and couldn't reproduce that bug. Maybe it is a MPS-specific error?

**Comment by rovo79** [comment]
Thanks for testing it out. 
I am upgraded to the latest nightly PyTorch. 
I usually run comfyui with "--force-fp16" argument. I also tried "--force-fp32" just incase, but didn't have an effect. 

My work-around at the moment was to disconnect the Zoe depth and put in place a Midas depth. I don't know what I'm doing, but so far it seems to be working.

<img width="944" alt="image" src="https://github.com/Fannovel16/comfyui_controlnet_aux/assets/117691/ea44b009-af59-4088-a0e9-d5bbfcd124da">

**Comment by Lightsockie** [comment]
I used to get a similar issue to the one in the OP, but uninstalling https://github.com/space-nuko/ComfyUI-Disco-Diffusion resolved it for me. Might check for any potential conflicts with other custom nodes (especially if you have this one).

**Comment by Fannovel16** [comment]
> I used to get a similar issue to the one in the OP, but uninstalling https://github.com/space-nuko/ComfyUI-Disco-Diffusion resolved it for me. Might check for any potential conflicts with other custom nodes (especially if you have this one).

I think the source of this issue is that midas_repo import "midas" which seems to conflict with "midas" from other repos https://github.com/Fannovel16/comfyui_controlnet_aux/blob/e6c9efb95f80b18c5f31a83fc20cc067a2aab738/src/controlnet_aux/zoe/zoedepth/models/base_models/midas_repo/midas/model_loader.py#L4

**Comment by Fannovel16** [comment]
Can you guys test the new commit? I moved midas_repo to different location and rename stuffs `midas.dpt_depth` to `custom_midas_repo.midas.depth`  to avoid conflicts.
https://github.com/Fannovel16/comfyui_controlnet_aux/commit/adbce8dd8753ac2d3a715b844fedf45e63943f2c

**Comment by Lightsockie** [comment]
I think I actually can't retest this repo's `Zoe-DepthMapPreprocessor` until https://github.com/Fannovel16/comfyui_controlnet_aux/issues/3 is resolved. I resolved this issue with this preproc on _the old repo_ by removing that conflicting custom_node provider. Here's my error for posterity:
```
KeyError: 'Zoe-DepthMapPreprocessor'
got prompt
Error handling request
Traceback (most recent call last):
  File "/home/gabriel/Work/StableDiffusion/ComfyUI/venv/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gabriel/Work/StableDiffusion/ComfyUI/venv/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gabriel/Work/StableDiffusion/ComfyUI/venv/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gabriel/Work/StableDiffusion/ComfyUI/server.py", line 42, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gabriel/Work/StableDiffusion/ComfyUI/server.py", line 442, in post_prompt
    valid = execution.validate_prompt(prompt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gabriel/Work/StableDiffusion/ComfyUI/execution.py", line 596, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
             ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'Zoe-DepthMapPreprocessor'
```
Currently on commit https://github.com/Fannovel16/comfyui_controlnet_aux/commit/2a0ee392ba089c918eee2fb11f8c29a87ea38e46
I'm using your provided test workflow from here, btw: https://github.com/Fannovel16/comfyui_controlnet_aux/blob/main/tests/test_cn_aux_full.json
(which seems to be looking for missing "LeReS-DepthMapPreprocessor" & "DWPreprocessor" custom nodes, btw)

**Comment by Fannovel16** [comment]
@Lightsockie I fixed https://github.com/Fannovel16/comfyui_controlnet_aux/issues/3. Can you try again?

**Comment by KevinParnell** [comment]
Up to date as of earlier this evening and receiving pretty much the same issue
`Error occurred when executing Zoe-DepthMapPreprocessor:

expected size to be one of int or Tuple[int] or Tuple[int, int] or Tuple[int, int, int], but got size with types [, ]

File "F:\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "F:\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "F:\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "F:\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\zoe.py", line 18, in execute
return (common_annotator_call(model, image), )
File "F:\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 28, in common_annotator_call
np_result = model(np_image, output_type="numpy", **kwargs)
File "F:\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\zoe\__init__.py", line 56, in __call__
depth = self.model.infer(image_depth)
File "F:\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\zoe\zoedepth\models\depth_model.py", line 126, in infer
return self.infer_with_flip_aug(x, pad_input=pad_input, **kwargs)
File "F:\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\zoe\zoedepth\models\depth_model.py", line 110, in infer_with_flip_aug
out = self._infer_with_pad_aug(x, pad_input=pad_input, **kwargs)
File "F:\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\zoe\zoedepth\models\depth_model.py", line 88, in _infer_with_pad_aug
out = self._infer(x)
File "F:\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\zoe\zoedepth\models\depth_model.py", line 55, in _infer
return self(x)['metric_depth']
File "F:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "F:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
File "F:\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\zoe\zoedepth\models\zoedepth\zoedepth_v1.py", line 144, in forward
rel_depth, out = self.core(x, denorm=denorm, return_rel_depth=True)
File "F:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "F:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
File "F:\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\zoe\zoedepth\models\base_models\midas.py", line 263, in forward
x = self.prep(x)
File "F:\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\zoe\zoedepth\models\base_models\midas.py", line 187, in __call__
return self.normalization(self.resizer(x))
File "F:\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\zoe\zoedepth\models\base_models\midas.py", line 174, in __call__
return nn.functional.interpolate(x, (height, width), mode='bilinear', align_corners=True)
File "F:\ComfyUI\venv\lib\site-packages\torch\nn\functional.py", line 3926, in interpolate
raise TypeError(`

**Comment by bissigb** [comment]
Hi,
i dont work an Mac, but had similar issues on Win with colab (as others had). Fixed it with the new repo https://github.com/Fannovel16/comfyui_controlnet_aux

**Comment by Pedroman1** [comment]
same issue as @rovo79 KevinParnell

**Comment by Lightsockie** [comment]
> @Lightsockie fixed https://github.com/Fannovel16/comfyui_controlnet_aux/issues/3. Can you try again?

Sorry about the delay, but confirming issue still exists. Only using this custom_node and ComfyUI-Manager
comfy: bc76b3829f5fbba7c5a439c7833d313a3ca87398
ComfyUI-Manager: 284e90dc8296a2e1e4f14b4b2d10fba2f52f0e53
control_aux: https://github.com/Fannovel16/comfyui_controlnet_aux/commit/f99b09b5bc659e68524e0b52a971d2e7f769caae

Same error as OP.
```
Python 3.11.3
torch==2.1.0.dev20230726+rocm5.6
torchaudio==2.1.0.dev20230727+rocm5.6
torchvision==0.16.0.dev20230727+rocm5.6
```

---

Also worth mentioning is around the time that when you did this

> I think the source of this issue is that midas_repo import "midas" which seems to conflict with "midas" from other repos
> 
> https://github.com/Fannovel16/comfyui_controlnet_aux/blob/e6c9efb95f80b18c5f31a83fc20cc067a2aab738/src/controlnet_aux/zoe/zoedepth/models/base_models/midas_repo/midas/model_loader.py#L4

I think you broke "compatibility" with with the old repo's Zoe. I had to disable custom_aux in my "real" install to have the old Zoe custom node work again. Won't matter once we get this new sexy workin' but figured I'd mention it

**Comment by kameleo333** [comment]
Hi M1max64go here I get this :
Error occurred when executing Zoe-DepthMapPreprocessor:

expected size to be one of int or Tuple[int] or Tuple[int, int] or Tuple[int, int, int], but got size with types [, ]

File "/Users/gbkm1max/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/Users/gbkm1max/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/Users/gbkm1max/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/Users/gbkm1max/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/zoe.py", line 19, in execute
out = common_annotator_call(model, image)
File "/Users/gbkm1max/ComfyUI/custom_nodes/comfyui_controlnet_aux/utils.py", line 28, in common_annotator_call
np_result = model(np_image, output_type="np", **kwargs)
File "/Users/gbkm1max/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/zoe/__init__.py", line 56, in __call__
depth = self.model.infer(image_depth)
File "/Users/gbkm1max/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/zoe/zoedepth/models/depth_model.py", line 126, in infer
return self.infer_with_flip_aug(x, pad_input=pad_input, **kwargs)
File "/Users/gbkm1max/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/zoe/zoedepth/models/depth_model.py", line 110, in infer_with_flip_aug
out = self._infer_with_pad_aug(x, pad_input=pad_input, **kwargs)
File "/Users/gbkm1max/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/zoe/zoedepth/models/depth_model.py", line 88, in _infer_with_pad_aug
out = self._infer(x)
File "/Users/gbkm1max/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/zoe/zoedepth/models/depth_model.py", line 55, in _infer
return self(x)['metric_depth']
File "/Users/gbkm1max/.pyenv/versions/3.9.2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/Users/gbkm1max/.pyenv/versions/3.9.2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
File "/Users/gbkm1max/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/zoe/zoedepth/models/zoedepth/zoedepth_v1.py", line 144, in forward
rel_depth, out = self.core(x, denorm=denorm, return_rel_depth=True)
File "/Users/gbkm1max/.pyenv/versions/3.9.2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/Users/gbkm1max/.pyenv/versions/3.9.2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
File "/Users/gbkm1max/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/zoe/zoedepth/models/base_models/midas.py", line 265, in forward
x = self.prep(x)
File "/Users/gbkm1max/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/zoe/zoedepth/models/base_models/midas.py", line 189, in __call__
return self.normalization(self.resizer(x))
File "/Users/gbkm1max/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/zoe/zoedepth/models/base_models/midas.py", line 176, in __call__
return nn.functional.interpolate(x, (height, width), mode='bilinear', align_corners=True)
File "/Users/gbkm1max/.pyenv/versions/3.9.2/lib/python3.9/site-packages/torch/nn/functional.py", line 3926, in interpolate
raise TypeError(

**Comment by gnadenlos** [comment]
Same error on Windows 11 with Python 3.11.6 and torch 2.1.0+cu121.

**Comment by cubiq** [comment]
this also happens on linux/cuda

to fix this:
file /comfyui_controlnet_aux/src/controlnet_aux/zoe/zoedepth/models/base_models/midas.py replace line 176 with

```return nn.functional.interpolate(x, (int(height), int(width)), mode='bilinear', align_corners=True)```

file /comfyui_controlnet_aux/src/custom_midas_repo/midas/backbones/beit.py replace line 47 with

```new_sub_table = F.interpolate(old_sub_table, size=(int(new_height), int(new_width)), mode="bilinear")```

**Comment by JPS-GER** [comment]
> to fix this

Your fix worked for me.

**Comment by JxinBain** [comment]
> > to fix this
> 
> Your fix worked for me. Thanks.

it does worked in windows alse.can you merge it to the master branch.

**Comment by SuperUserNameMan** [comment]
@cubiq : thank for the fix. 

No one willing to create a PR ?

**Comment by cubiq** [comment]
PR #71 pushed

**Comment by kameleo333** [comment]
> this also happens on linux/cuda
> 
> to fix this: file /comfyui_controlnet_aux/src/controlnet_aux/zoe/zoedepth/models/base_models/midas.py replace line 176 with
> 
> `return nn.functional.interpolate(x, (int(height), int(width)), mode='bilinear', align_corners=True)`
> 
> file /comfyui_controlnet_aux/src/custom_midas_repo/midas/backbones/beit.py replace line 47 with
> 
> `new_sub_table = F.interpolate(old_sub_table, size=(int(new_height), int(new_width)), mode="bilinear")`
Tried you code change and now I get this (M1Max64go) :

Error occurred when executing Zoe-DepthMapPreprocessor:

The operator 'aten::upsample_bicubic2d.out' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

File "/Users/gbkm1max/ComfyUI/execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/Users/gbkm1max/ComfyUI/execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/Users/gbkm1max/ComfyUI/execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/Users/gbkm1max/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/zoe.py", line 19, in execute
out = common_annotator_call(model, image)
File "/Users/gbkm1max/ComfyUI/custom_nodes/comfyui_controlnet_aux/utils.py", line 28, in common_annotator_call
np_result = model(np_image, output_type="np", **kwargs)
File "/Users/gbkm1max/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/zoe/__init__.py", line 56, in __call__
depth = self.model.infer(image_depth)
File "/Users/gbkm1max/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/zoe/zoedepth/models/depth_model.py", line 126, in infer
return self.infer_with_flip_aug(x, pad_input=pad_input, **kwargs)
File "/Users/gbkm1max/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/zoe/zoedepth/models/depth_model.py", line 110, in infer_with_flip_aug
out = self._infer_with_pad_aug(x, pad_input=pad_input, **kwargs)
File "/Users/gbkm1max/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/zoe/zoedepth/models/depth_model.py", line 90, in _infer_with_pad_aug
out = F.interpolate(out, size=(x.shape[2], x.shape[3]), mode=upsampling_mode, align_corners=False)
File "/Users/gbkm1max/.pyenv/versions/3.9.2/lib/python3.9/site-packages/torch/nn/functional.py", line 4030, in interpolate
return torch._C._nn.upsample_bicubic2d(input, output_size, align_corners, scale_factors)

**Comment by Fannovel16** [comment]
@kameleo333 Fixed at https://github.com/Fannovel16/comfyui_controlnet_aux/commit/e3ac5efcbe6c9c131cc65607c940e60751d3d6fc

**Comment by WWddf112112313** [comment]
Error occurred when executing MiDaS-DepthMapPreprocessor:

Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

File "I:\Blender_ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "I:\Blender_ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "I:\Blender_ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "I:\Blender_ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux-main\node_wrappers\midas.py", line 45, in execute
model = MidasDetector.from_pretrained(HF_MODEL_NAME, cache_dir=annotator_ckpts_path).to(model_management.get_torch_device())
File "I:\Blender_ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux-main\src\controlnet_aux\midas\__init__.py", line 28, in from_pretrained
model_path = hf_hub_download(pretrained_model_or_path, filename, cache_dir=cache_dir)
File "I:\Blender_ComfyUI\python_embeded\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
return fn(*args, **kwargs)
File "I:\Blender_ComfyUI\python_embeded\lib\site-packages\huggingface_hub\file_download.py", line 1227, in hf_hub_download
raise LocalEntryNotFoundError(

Close
